# Generated by Django 4.2.17 on 2025-01-14 09:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('title', models.TextField(verbose_name='title')),
                ('title_en', models.TextField(null=True, verbose_name='title')),
                ('title_es', models.TextField(null=True, verbose_name='title')),
                ('title_fr', models.TextField(null=True, verbose_name='title')),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default=None, max_length=6, null=True, verbose_name='priority')),
                ('implementor', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('hq', 'HQ'), ('all', 'All')], default=None, max_length=8, null=True, verbose_name='implementor')),
                ('rank', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='rank')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('title', models.TextField(verbose_name='title')),
                ('title_en', models.TextField(null=True, verbose_name='title')),
                ('title_es', models.TextField(null=True, verbose_name='title')),
                ('title_fr', models.TextField(null=True, verbose_name='title')),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default=None, max_length=6, null=True, verbose_name='priority')),
                ('implementor', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('hq', 'HQ'), ('all', 'All')], default=None, max_length=8, null=True, verbose_name='implementor')),
                ('rank', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='rank')),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('weightage', models.FloatField(verbose_name='weightage')),
                ('version', models.CharField(max_length=255, verbose_name='version')),
                ('is_active', models.BooleanField(default=False, editable=False, verbose_name='active')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('weightage', models.FloatField(verbose_name='weightage')),
                ('version', models.CharField(max_length=255, verbose_name='version')),
                ('is_active', models.BooleanField(default=False, editable=False, verbose_name='active')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('title', models.TextField(verbose_name='title')),
                ('title_en', models.TextField(null=True, verbose_name='title')),
                ('title_es', models.TextField(null=True, verbose_name='title')),
                ('title_fr', models.TextField(null=True, verbose_name='title')),
                ('hints', models.TextField(blank=True, default=None, null=True, verbose_name='hints')),
                ('hints_en', models.TextField(blank=True, default=None, null=True, verbose_name='hints')),
                ('hints_es', models.TextField(blank=True, default=None, null=True, verbose_name='hints')),
                ('hints_fr', models.TextField(blank=True, default=None, null=True, verbose_name='hints')),
                ('is_experimental', models.BooleanField(default=False, verbose_name='experimental')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatementFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('formula', models.TextField(verbose_name='formula')),
                ('version', models.CharField(max_length=255, verbose_name='version')),
                ('is_active', models.BooleanField(default=False, editable=False, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='StatementTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='title')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatementTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='title')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatementTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('icon', models.FileField(blank=True, default=None, null=True, upload_to='statement/statement_topic/icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png'])], verbose_name='icon')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, default=None, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, default=None, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, default=None, null=True, verbose_name='description')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_topics', to='context.context', verbose_name='context')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
