# Generated by Django 4.2.17 on 2025-01-14 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        ('statement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('context', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementtopic',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='statementtopic',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='statementtaggroup',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='statementtaggroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='statementtag',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='statementtag',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='statement.statementtaggroup', verbose_name='statement tag group'),
        ),
        migrations.AddField(
            model_name='statementtag',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='statementformula',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='statementformula',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='context.module', verbose_name='module'),
        ),
        migrations.AddField(
            model_name='statementformula',
            name='question_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='survey.questiongroup', verbose_name='question group'),
        ),
        migrations.AddField(
            model_name='statementformula',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='statement.statement', verbose_name='statement'),
        ),
        migrations.AddField(
            model_name='statementformula',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='statement',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='statement',
            name='options',
            field=models.ManyToManyField(related_name='statements', through='statement.OptionStatement', to='survey.option', verbose_name='options'),
        ),
        migrations.AddField(
            model_name='statement',
            name='questions',
            field=models.ManyToManyField(related_name='statements', through='statement.QuestionStatement', to='survey.question', verbose_name='questions'),
        ),
        migrations.AddField(
            model_name='statement',
            name='tags',
            field=models.ManyToManyField(related_name='statements', to='statement.statementtag', verbose_name='statement tags'),
        ),
        migrations.AddField(
            model_name='statement',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='statement.statementtopic', verbose_name='statement topic'),
        ),
        migrations.AddField(
            model_name='statement',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='question_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='question group'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statement', verbose_name='statement'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='optionstatement',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='optionstatement',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.option', verbose_name='option'),
        ),
        migrations.AddField(
            model_name='optionstatement',
            name='question_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='question group'),
        ),
        migrations.AddField(
            model_name='optionstatement',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statement', verbose_name='statement'),
        ),
        migrations.AddField(
            model_name='optionstatement',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='survey.option', verbose_name='options'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='statements',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='statement.statement', verbose_name='statements'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='mitigations', to='survey.option', verbose_name='options'),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='statements',
            field=models.ManyToManyField(blank=True, related_name='mitigations', to='statement.statement', verbose_name='statements'),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddConstraint(
            model_name='statementformula',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', True)), fields=('statement', 'version'), name='one_version_formula_statement'),
        ),
        migrations.AddConstraint(
            model_name='statementformula',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', True)), fields=('statement',), name='one_active_version_formula_statement'),
        ),
        migrations.AddConstraint(
            model_name='statementformula',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', False)), fields=('question_group', 'statement', 'version'), name='one_version_formula_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='statementformula',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', False)), fields=('question_group', 'statement'), name='one_active_formula_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', True)), fields=('question', 'statement', 'version'), name='unique_version_question_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', True)), fields=('question', 'statement'), name='one_active_question_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', False)), fields=('question', 'statement', 'question_group', 'version'), name='unique_version_question_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', False)), fields=('question', 'statement', 'question_group'), name='one_active_question_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', True)), fields=('option', 'statement', 'version'), name='unique_version_option_statement'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', True)), fields=('option', 'statement'), name='one_active_option_statement'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', False)), fields=('option', 'statement', 'question_group', 'version'), name='unique_version_option_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', False)), fields=('option', 'statement', 'question_group'), name='one_active_option_question_group_statement'),
        ),
    ]
