# Generated by Django 3.2.12 on 2022-02-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0004_add_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstatement',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='optionstatement',
            name='version',
            field=models.CharField(default='initial', max_length=255, verbose_name='version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='version',
            field=models.CharField(default='initial', max_length=255, verbose_name='version'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(fields=('option', 'statement', 'version'), name='unique_version_option_statement'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('option', 'statement'), name='one_active_option_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(fields=('question', 'statement', 'version'), name='unique_version_question_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('question', 'statement'), name='one_active_question_statement'),
        ),
    ]
