# Generated by Django 3.2.12 on 2022-02-16 06:21

from django.db import migrations

def forward_migration(apps, schema_editor):
    QuestionStatement = apps.get_model('statement', 'QuestionStatement')
    OptionStatement = apps.get_model('statement', 'OptionStatement')

    QuestionStatement.objects.filter(version="initial").update(is_active=True)
    OptionStatement.objects.filter(version="initial").update(is_active=True)

class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0005_statement_question_option_version'),
    ]

    operations = [
        migrations.RunPython(forward_migration, migrations.RunPython.noop)
    ]
