# Generated by Django 3.2.12 on 2022-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0006_make_initial_version_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigation',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='statementtopic',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
    ]
