# Generated by Django 3.2.12 on 2022-02-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0007_increase_code_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionopportunity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='optionopportunity',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='optionopportunity',
            name='option',
        ),
        migrations.RemoveField(
            model_name='optionopportunity',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='mitigation',
            name='options',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='options',
        ),
        migrations.DeleteModel(
            name='OptionMitigation',
        ),
        migrations.DeleteModel(
            name='OptionOpportunity',
        ),
    ]
