# Generated by Django 3.2.12 on 2022-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_option_mitigation_opportunity_json_field'),
        ('statement', '0008_delete_option_mitigation_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='question_groups',
            field=models.ManyToManyField(related_name='statements', to='survey.QuestionGroup', verbose_name='question groups'),
        ),
    ]
