# Generated by Django 3.2.12 on 2022-03-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_option_mitigation_opportunity_json_field'),
        ('statement', '0009_statement_question_groups'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='optionstatement',
            name='unique_version_option_statement',
        ),
        migrations.RemoveConstraint(
            model_name='optionstatement',
            name='one_active_option_statement',
        ),
        migrations.RemoveConstraint(
            model_name='questionstatement',
            name='unique_version_question_statement',
        ),
        migrations.RemoveConstraint(
            model_name='questionstatement',
            name='one_active_question_statement',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='question_groups',
        ),
        migrations.AddField(
            model_name='optionstatement',
            name='question_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='question group'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='question_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.questiongroup', verbose_name='question group'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', True)), fields=('option', 'statement', 'version'), name='unique_version_option_statement'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', True)), fields=('option', 'statement'), name='one_active_option_statement'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', False)), fields=('option', 'statement', 'question_group', 'version'), name='unique_version_option_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='optionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', False)), fields=('option', 'statement', 'question_group'), name='one_active_option_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', True)), fields=('question', 'statement', 'version'), name='unique_version_question_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', True)), fields=('question', 'statement'), name='one_active_question_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', False)), fields=('question', 'statement', 'question_group', 'version'), name='unique_version_question_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='questionstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', False)), fields=('question', 'statement', 'question_group'), name='one_active_question_question_group_statement'),
        ),
    ]
