# Generated by Django 3.2.13 on 2022-06-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0011_create_statement_formula'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statementformula',
            name='one_formula_question_group_statement',
        ),
        migrations.RemoveConstraint(
            model_name='statementformula',
            name='one_formula_statement',
        ),
        migrations.AddField(
            model_name='statementformula',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='statementformula',
            name='version',
            field=models.CharField(default='initial', max_length=255, verbose_name='version'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='statementformula',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', True)), fields=('statement', 'version'), name='one_version_formula_statement'),
        ),
        migrations.AddConstraint(
            model_name='statementformula',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', True)), fields=('statement',), name='one_active_version_formula_statement'),
        ),
        migrations.AddConstraint(
            model_name='statementformula',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', False)), fields=('question_group', 'statement', 'version'), name='one_version_formula_question_group_statement'),
        ),
        migrations.AddConstraint(
            model_name='statementformula',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('question_group__isnull', False)), fields=('question_group', 'statement'), name='one_active_formula_question_group_statement'),
        ),
    ]
