# Generated by Django 3.2.18 on 2023-02-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0012_create_statement_formula_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ('order',), 'verbose_name_plural': 'opportunities'},
        ),
        migrations.AddField(
            model_name='mitigation',
            name='statements',
            field=models.ManyToManyField(blank=True, related_name='mitigations', to='statement.Statement', verbose_name='statements'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='statements',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='statement.Statement', verbose_name='statements'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statement.statement'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statement.statement'),
        ),
    ]
