# Generated by Django 3.2.18 on 2023-02-28 09:57

from django.db import migrations

def forward_migration(apps, schema_editor):
    Mitigation = apps.get_model('statement', 'Mitigation')
    Opportunity = apps.get_model('statement', 'Opportunity')
    for mitigation in Mitigation.objects.all():
        mitigation.statements.add(mitigation.statement)
    for opportunity in Opportunity.objects.all():
        opportunity.statements.add(opportunity.statement)

def backward_migration(apps, schema_editor):
    Mitigation = apps.get_model('statement', 'Mitigation')
    Opportunity = apps.get_model('statement', 'Opportunity')
    for mitigation in Mitigation.objects.all():
        mitigation.statement = mitigation.statements.first()
        mitigation.save()
    for opportunity in Opportunity.objects.all():
        opportunity.statement = opportunity.statements.first()
        opportunity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0013_mitigation_opportunity_multiple_statement'),
    ]

    operations = [migrations.RunPython(forward_migration, backward_migration)]
