# Generated by Django 3.2.18 on 2023-02-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_json_field_blank_true_default'),
        ('statement', '0014_single_statement_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigation',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='statement',
        ),
        migrations.AddField(
            model_name='mitigation',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='mitigations', to='survey.Option', verbose_name='options'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='survey.Option', verbose_name='options'),
        ),
    ]
