version: 2
updates:
  # maintain poetry dependencies daily
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # maintain github actions dependencies daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
