version: 2
updates:
  # maintain poetry dependencies weekly
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  # maintain github actions dependencies weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
