version: 2
updates:
  # maintain poetry dependencies monthly
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
  # maintain github actions dependencies monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
