fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black . --check
      pass_filenames: false
      language: system
    - id: isort
      name: isort
      entry: poetry run isort . --check-only
      pass_filenames: false
      language: system
    - id: safety
      name: safety
      entry: poetry run safety check --ignore 40291 # pip <21.1 affected
      pass_filenames: false
      language: system
