version: "3.7"

services:
  server:
    container_name: "${COMPOSE_PROJECT_NAME}"
    env_file: .env
    image: ghcr.io/neatplus/server:latest
    ports:
      - "8000:8000"
    networks:
      - default
      - external-services

networks:
  external-services:
    external: true
