version: "3.7"

services:
  db:
    container_name: postgis
    image: postgis/postgis:13-3.1-alpine
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
    - external-services

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
    - redis-data:/data
    networks:
    - external-services

networks:
  external-services:
    external: true

volumes:
  postgres-data:
    name: postgres-data
  redis-data:
    name: redis-data
