[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
extend-exclude = "migrations/"

[tool.isort]
skip_glob = ["__pycache__", "**/migrations"]
profile = "black"

[tool.poetry]
name = "neatplus-server"
version = "0.0.1"
description = "Neatplus server"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.4"
environs = {version = "^9.3.2", extras = ["django"]}
marshmallow = "^3.12.1"
uvicorn = {version = "^0.14.0", extras = ["standard"], optional=true}
gunicorn = {version="^20.1.0", optional=true}
psycopg2-binary = "^2.9.1"
djangorestframework = "^3.12.4"
django-filter = "^2.4.0"
djangorestframework-simplejwt = "^4.7.1"
djangorestframework-camel-case = "^1.2.0"
django-admin-interface = "^0.16.3"
django-otp = "^1.0.6"
qrcode = "^6.1"
django-cors-headers = "^3.7.0"
django-silk = "^4.1.0"
django-storages = "^1.11.1"
sentry-sdk = "^1.1.0"
celery = "^5.1.1"
redis = "^3.5.3"
django-modeltranslation = "^0.17.2"
django-ordered-model = "^3.4.3"
drf-spectacular = "^0.17.2"
Pillow = "^8.2.0"
django-ckeditor = "^6.1.0"
djangorestframework-gis = "^0.17"
django-admin-autocomplete-filter = {git = "https://github.com/farhan0581/django-admin-autocomplete-filter", rev = "e6ebfe50777b326bec49220546c3fc0bc2fca27d"}

[tool.poetry.dev-dependencies]
black = "^21.6b0"
isort = "^5.8.0"
safety = "^1.10.3"
pre-commit = "^2.13.0"
django-extensions = "^3.1.3"
ptpython = "^3.0.17"
ipython = "^7.24.1"
Werkzeug = "^2.0.1"
pyparsing = "^2.4.7"
pydot = "^1.4.2"
model-bakery = "^1.3.2"

[tool.poetry.extras]
asgi = ["uvicorn", "gunicorn"]
