[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = "migrations/"

[tool.isort]
skip_glob = ["__pycache__", "**/migrations"]
profile = "black"

[tool.poetry]
name = "neatplus-server"
version = "0.0.1"
description = "Neatplus server"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.1.7"
environs = {version = "^9.3.1", extras = ["django"]}
marshmallow = "^3.10.0"
uvicorn = {version = "^0.13.4", extras = ["standard"], optional=true}
gunicorn = {version="^20.0.4", optional=true}
psycopg2-binary = "^2.8.6"
djangorestframework = "^3.12.2"
django-filter = "^2.4.0"
djangorestframework-simplejwt = "^4.6.0"
djangorestframework-camel-case = "^1.2.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
safety = "^1.10.3"
pre-commit = "^2.10.1"

[tool.poetry.extras]
asgi = ["uvicorn", "gunicorn"]
