[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "neatplus-server"
version = "0.0.1"
description = "Neatplus server"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"
Django = "^3.1.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
safety = "^1.10.3"
