[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
extend-exclude = "migrations/"

[tool.isort]
skip_glob = ["__pycache__", "**/migrations"]
profile = "black"

[tool.poetry]
name = "neatplus-server"
version = "0.0.1"
description = "Neatplus server"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.8"
environs = { version = "^9.3.3", extras = ["django"] }
marshmallow = "^3.13.0"
uvicorn = { version = "^0.15.0", extras = ["standard"], optional = true }
gunicorn = { version = "^20.1.0", optional = true }
psycopg2-binary = "^2.9.1"
djangorestframework = "^3.12.4"
django-filter = "^21.1"
djangorestframework-simplejwt = "^4.8.0"
djangorestframework-camel-case = "^1.2.0"
django-admin-interface = "^0.17.1"
django-otp = "^1.1.1"
qrcode = "^7.3"
django-cors-headers = "^3.9.0"
django-silk = "^4.2.0"
django-storages = { version = "^1.11.1", extras = ["boto3"] }
sentry-sdk = "^1.4.3"
celery = "^5.1.2"
redis = "^3.5.3"
django-modeltranslation = "^0.17.3"
django-ordered-model = "^3.4.3"
drf-spectacular = "^0.20.2"
Pillow = "^9.0.0"
django-ckeditor = "^6.1.0"
djangorestframework-gis = "^0.17"
django-admin-autocomplete-filter = "^0.7.1"
drf-recaptcha = "^2.0.4"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
isort = "^5.9.3"
safety = "^1.10.3"
pre-commit = "^2.15.0"
django-extensions = "^3.1.3"
ptpython = "^3.0.20"
ipython = "^7.28.0"
Werkzeug = "^2.0.1"
pyparsing = "^2.4.7"
pydot = "^1.4.2"
model-bakery = "^1.3.2, !=1.3.3"

[tool.poetry.extras]
asgi = ["uvicorn", "gunicorn"]
