# Generated by Django 3.2.4 on 2021-06-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_member_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='organization/organization/logos'),
        ),
    ]
