# Generated by Django 3.2.4 on 2021-07-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='acronym',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
