# Generated by Django 3.2.12 on 2022-02-10 11:26

from django.db import migrations
from mptt import register, managers

def forward_migration(apps, schema_editor):
    Organization = apps.get_model('organization', 'Organization')

    manager = managers.TreeManager()
    manager.model = Organization

    register(Organization)

    manager.contribute_to_class(Organization, 'objects')
    manager.rebuild()

class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_mptt'),
    ]

    operations = [
        migrations.RunPython(forward_migration, migrations.RunPython.noop)
    ]
