apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert_issuer.yml
  - certificate.yml
  - superset_certificate.yml
patches:
  - target:
      labelSelector: "app.kubernetes.io/name=letsencrypt-issuer"
    patch: |-
      - op: replace
        path: /spec/acme/email
        value: ${CERT_EMAIL_ADDRESS}
  - target:
      labelSelector: "app.kubernetes.io/name=acme-certificate"
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: ${PROJECT_HOST_URL}
  - target:
      labelSelector: "app.kubernetes.io/name=superset-acme-certificate"
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: ${SUPERSET_HOST_URL}
