apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: superset-acme-certificate
  labels:
    app.kubernetes.io/name: superset-acme-certificate
spec:
  secretName: superset-cert-secret
  dnsNames:
  - example.com
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
