# Generated by Django 4.2.17 on 2025-01-14 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0002_initial'),
        ('statement', '0002_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresultfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='surveyresultfeedback',
            name='survey_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='summary.surveyresult', verbose_name='survey result'),
        ),
        migrations.AddField(
            model_name='surveyresultfeedback',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='context.module', verbose_name='module'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='question_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='survey.questiongroup', verbose_name='question group'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statement', verbose_name='statement'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='survey.survey', verbose_name='survey'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddConstraint(
            model_name='surveyresultfeedback',
            constraint=models.UniqueConstraint(condition=models.Q(('is_baseline', True)), fields=('survey_result',), name='survey_result_one_baseline'),
        ),
        migrations.AddConstraint(
            model_name='surveyresult',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', True)), fields=('statement', 'survey', 'module'), name='unique_module_survey_statement'),
        ),
        migrations.AddConstraint(
            model_name='surveyresult',
            constraint=models.UniqueConstraint(condition=models.Q(('question_group__isnull', False)), fields=('statement', 'survey', 'module', 'question_group'), name='unique_module_survey_question_group_statement'),
        ),
    ]
