# Generated by Django 3.2.4 on 2021-06-15 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_questionstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementtopic',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='statementtopic',
            name='description_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='statementtopic',
            name='description_es',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='statementtopic',
            name='description_fr',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statementtopic',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='summary/statement_topic/icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png'])]),
        ),
    ]
