# Generated by Django 3.2.8 on 2021-11-08 11:27

from django.db import migrations
from django.db.migrations import exceptions


def forward_migration(apps, schema_editor):
    Module = apps.get_model('context', 'Module')
    SurveyResult = apps.get_model('summary', 'SurveyResult')
    default_module = Module.objects.first()
    for survey_result in SurveyResult.objects.filter(module__isnull=True):
        survey = survey_result.survey
        answer = survey.answers.first()
        if answer is None:
            raise exceptions.InvalidMigrationPlan(
                f'Survey {survey.pk} has no answer. Migration does not support such survey'
            )
        modules = list(survey.answers.values_list('question__module', flat=True))
        non_null_modules = [ x for x in modules if x is not None]
        if not non_null_modules:
            if default_module is None:
                raise exceptions.InvalidMigrationPlan(
                    'Cannot set default module since there is no single module. Create at least one module'
                )
            module = default_module
        else:
            module_id = max(non_null_modules, key=non_null_modules.count)
            module = Module.objects.get(id=module_id)
        survey_result.module = module
        survey_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_surveyresult_module'),
    ]

    operations = [
        migrations.RunPython(forward_migration, migrations.RunPython.noop)
    ]
