# Generated by Django 3.2.4 on 2021-06-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_alter_statementtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementtopic',
            options={'ordering': ('order',)},
        ),
    ]
