# Generated by Django 3.2.12 on 2022-02-10 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_add_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0010_add_verbose_name'),
        ('statement', '0004_add_verbose_name'),
        ('summary', '0004_survey_result_module_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='context.module', verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='score',
            field=models.FloatField(verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statement', verbose_name='statement'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='survey.survey', verbose_name='survey'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
