# Generated by Django 3.2.4 on 2021-06-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_alter_statementtopic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstatement',
            name='weightage',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='weightage',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
