# Generated by Django 3.2.12 on 2022-03-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_surveyresultfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresultfeedback',
            name='expected_score',
            field=models.FloatField(verbose_name='expected score'),
        ),
    ]
