# Generated by Django 3.2.12 on 2022-03-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_alter_surveyresultfeedback_expected_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresultfeedback',
            name='is_baseline',
            field=models.BooleanField(default=False, verbose_name='baseline'),
        ),
    ]
