# Generated by Django 3.2.12 on 2022-04-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_surveyresultfeedback_is_baseline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresult',
            options={'permissions': [('add_baseline_feedback', 'Can add baseline feedback')]},
        ),
    ]
