# Generated by Django 3.2.13 on 2022-06-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_alter_surveyresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresultfeedback',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='comment'),
        ),
    ]
