# Generated by Django 4.2.17 on 2025-01-14 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='description')),
                ('notice_type', models.CharField(choices=[('user', 'User'), ('public', 'Public')], default='public', max_length=6, verbose_name='notice type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('actor_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='actor object id')),
                ('verb', models.CharField(max_length=100, verbose_name='verb')),
                ('description', models.TextField(verbose_name='description')),
                ('notification_type', models.CharField(default='default', max_length=50, verbose_name='notification type')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('action_object_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='action object object id')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='target object id')),
                ('has_read', models.BooleanField(default=False, editable=False, verbose_name='read')),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_action_object', to='contenttypes.contenttype', verbose_name='action object content type')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.contenttype', verbose_name='actor content type')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
