# Generated by Django 4.2.17 on 2025-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_add_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
    ]
