apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - superset.yml
  - service.yml
secretGenerator:
  - name: superset-secret
    envs:
      - superset.env
    type: Opaque
configMapGenerator:
  - name: superset-config-map
    files:
      - superset_config.py
patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: superset-secret
        labels:
          app: superset
          project: neatplus
          role: dashboard
  - patch: |-
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: superset-config-map
          labels:
            app: superset
            project: neatplus
            role: dashboard
