apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yml
  - superset_ingress.yml
patches:
  - target:
      labelSelector: "app.kubernetes.io/name=server-ingress"
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ${PROJECT_HOST_URL}
      - op: replace
        path: /spec/rules/0/host
        value: ${PROJECT_HOST_URL}
  - target:
      labelSelector: "app.kubernetes.io/name=superset-ingress"
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ${SUPERSET_HOST_URL}
      - op: replace
        path: /spec/rules/0/host
        value: ${SUPERSET_HOST_URL}
