version: "3.7"

services:
  server:
    container_name: "${PROJECT_NAME}"
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    volumes:
      - .:/code
    networks:
      - default
      - external-services

networks:
  external-services:
    external: true
