# Generated by Django 4.2.17 on 2025-01-14 09:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('organization', models.CharField(max_length=255, verbose_name='organization')),
                ('summary', models.TextField(verbose_name='summary')),
                ('summary_en', models.TextField(null=True, verbose_name='summary')),
                ('summary_es', models.TextField(null=True, verbose_name='summary')),
                ('summary_fr', models.TextField(null=True, verbose_name='summary')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='description')),
                ('description_es', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='description')),
                ('description_fr', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='description')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='point')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='identifier')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('html_message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='html message')),
                ('text_message', models.TextField(verbose_name='text message')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('question', models.TextField(verbose_name='question')),
                ('question_en', models.TextField(null=True, verbose_name='question')),
                ('question_es', models.TextField(null=True, verbose_name='question')),
                ('question_fr', models.TextField(null=True, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_en', models.TextField(null=True, verbose_name='answer')),
                ('answer_es', models.TextField(null=True, verbose_name='answer')),
                ('answer_fr', models.TextField(null=True, verbose_name='answer')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('document_type', models.CharField(choices=[('terms-and-conditions', 'Terms And Conditions'), ('privacy-policy', 'Privacy Policy'), ('cookie-policy', 'Cookie Policy')], max_length=20, unique=True, verbose_name='document type')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='description')),
                ('description_es', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='description')),
                ('description_fr', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('description_fr', models.TextField(null=True, verbose_name='description')),
                ('resource_type', models.CharField(choices=[('attachment', 'Attachment'), ('video', 'Video')], max_length=10, verbose_name='resource type')),
                ('video_url', models.URLField(blank=True, default=None, null=True, verbose_name='video url')),
                ('attachment', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='attachment')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
