# Generated by Django 3.2.3 on 2021-05-28 07:31

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_resource_resourcetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_es', models.TextField(null=True)),
                ('summary_fr', models.TextField(null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_es', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_fr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
