# Generated by Django 3.2.4 on 2021-06-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('support', '0003_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='context',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='context.context'),
        ),
    ]
