# Generated by Django 3.2.4 on 2021-06-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_action_context'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('order',)},
        ),
    ]
