# Generated by Django 3.2.5 on 2021-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_legaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms-and-conditions', 'Terms And Conditions'), ('privacy-policy', 'Privacy Policy'), ('cookie-policy', 'Cookie Policy')], max_length=20, unique=True),
        ),
    ]
