# Generated by Django 3.2.11 on 2022-02-09 12:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_legaldocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_message', ckeditor.fields.RichTextField()),
                ('text_message', models.TextField()),
            ],
        ),
    ]
