# Generated by Django 3.2.12 on 2022-02-10 14:40

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_add_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0008_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='context',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='context.context', verbose_name='context'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='action',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='action',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='point'),
        ),
        migrations.AlterField(
            model_name='action',
            name='summary',
            field=models.TextField(verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='action',
            name='summary_en',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='action',
            name='summary_es',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='action',
            name='summary_fr',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_message',
            field=ckeditor.fields.RichTextField(verbose_name='html mesaage'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text_message',
            field=models.TextField(verbose_name='text message'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer_es',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer_fr',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question_en',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question_es',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question_fr',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_es',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_fr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms-and-conditions', 'Terms And Conditions'), ('privacy-policy', 'Privacy Policy'), ('cookie-policy', 'Cookie Policy')], max_length=20, unique=True, verbose_name='document type'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('attachment', 'Attachment'), ('video', 'Video')], max_length=10, verbose_name='resource type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(related_name='resources', to='support.ResourceTag', verbose_name='resource tags'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='video_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='video url'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
