# Generated by Django 3.2.13 on 2022-05-27 05:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_add_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_message',
            field=ckeditor.fields.RichTextField(verbose_name='html message'),
        ),
    ]
