# Generated by Django 4.2.17 on 2025-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_alter_emailtemplate_html_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_message',
            field=models.TextField(verbose_name='html message'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
