apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
  labels:
    app: celery-worker
    project: neatplus
    role: backend
spec:
  selector:
    matchLabels:
      app: celery-worker
      project: neatplus
      role: backend
  template:
    metadata:
      name: celery-worker-pod
      labels:
        app: celery-worker
        project: neatplus
        role: backend
    spec:
      containers:
      - name: container
        image: ghcr.io/neatplus/server:latest
        env:
          - name: CELERY_WORKER
            value: "true"
        envFrom:
          - secretRef:
              name: server-secret
