apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - server.yml
  - celery_worker.yml
  - service.yml
secretGenerator:
  - name: server-secret
    envs:
      - .env
    type: Opaque
replicas:
  - name: server-deployment
    count: ${SERVER_REPLICA_COUNT}
  - name: celery-worker-deployment
    count: ${CELERY_WORKER_REPLICA_COUNT}
images:
  - name: ghcr.io/neatplus/server
    newTag: ${PROJECT_VERSION}
