apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  labels:
    app.kubernetes.io/name: issuer
spec:
  acme:
    email: user@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: neatplus-issuer-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
