# Generated by Django 3.2.5 on 2021-07-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='share_analytics_with_neat',
            field=models.BooleanField(default=False),
        ),
    ]
