# Generated by Django 4.2.17 on 2025-01-14 09:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import neatplus.fields
import user.auth_validators
import user.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', neatplus.fields.LowerCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Length can be between 5 to 20. Letters, digits and ./-/_ only.', max_length=20, unique=True, validators=[user.auth_validators.CustomASCIIUsernameValidator(), django.core.validators.MinLengthValidator(limit_value=5)], verbose_name='username')),
                ('email', neatplus.fields.LowerEmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('organization', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='organization')),
                ('role', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='role')),
                ('has_accepted_terms_and_privacy_policy', models.BooleanField(default=True, verbose_name='accepted terms and privacy policy')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', user.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserOldPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_passwords', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('no_of_incorrect_attempts', models.PositiveIntegerField(default=0, verbose_name='number of incorrect attempts')),
                ('pin', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='pin')),
                ('pin_expiry_time', models.DateTimeField(verbose_name='pin expiry time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('identifier', models.CharField(max_length=16, verbose_name='identifier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_pin', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmationPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('no_of_incorrect_attempts', models.PositiveIntegerField(default=0, verbose_name='number of incorrect attempts')),
                ('pin', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='pin')),
                ('pin_expiry_time', models.DateTimeField(verbose_name='pin expiry time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirm_pin', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailChangePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('no_of_incorrect_attempts', models.PositiveIntegerField(default=0, verbose_name='number of incorrect attempts')),
                ('pin', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='pin')),
                ('pin_expiry_time', models.DateTimeField(verbose_name='pin expiry time')),
                ('new_email', neatplus.fields.LowerEmailField(max_length=254, verbose_name='new email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_pin', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
