# Generated by Django 3.2.5 on 2021-08-03 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import neatplus.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_has_accepted_terms_and_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('no_of_incorrect_attempts', models.PositiveIntegerField(default=0)),
                ('pin', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)])),
                ('pin_expiry_time', models.DateTimeField()),
                ('new_email', neatplus.fields.LowerEmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
