# Generated by Django 3.2.12 on 2022-02-10 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import neatplus.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useroldpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchangepin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='emailchangepin',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='emailchangepin',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='emailchangepin',
            name='new_email',
            field=neatplus.fields.LowerEmailField(max_length=254, verbose_name='new email'),
        ),
        migrations.AlterField(
            model_name='emailchangepin',
            name='no_of_incorrect_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='number of incorrect attempts'),
        ),
        migrations.AlterField(
            model_name='emailchangepin',
            name='pin',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='pin'),
        ),
        migrations.AlterField(
            model_name='emailchangepin',
            name='pin_expiry_time',
            field=models.DateTimeField(verbose_name='pin expiry time'),
        ),
        migrations.AlterField(
            model_name='emailchangepin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_pin', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationpin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationpin',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationpin',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationpin',
            name='no_of_incorrect_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='number of incorrect attempts'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationpin',
            name='pin',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='pin'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationpin',
            name='pin_expiry_time',
            field=models.DateTimeField(verbose_name='pin expiry time'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationpin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirm_pin', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='passwordresetpin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='passwordresetpin',
            name='identifier',
            field=models.CharField(max_length=16, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='passwordresetpin',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='passwordresetpin',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='passwordresetpin',
            name='no_of_incorrect_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='number of incorrect attempts'),
        ),
        migrations.AlterField(
            model_name='passwordresetpin',
            name='pin',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='pin'),
        ),
        migrations.AlterField(
            model_name='passwordresetpin',
            name='pin_expiry_time',
            field=models.DateTimeField(verbose_name='pin expiry time'),
        ),
        migrations.AlterField(
            model_name='passwordresetpin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_pin', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_accepted_terms_and_privacy_policy',
            field=models.BooleanField(default=True, verbose_name='accepted terms and privacy policy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='useroldpassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='useroldpassword',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='useroldpassword',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='useroldpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_passwords', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
