# Generated by Django 3.2.4 on 2021-06-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_add_skip_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
