# Generated by Django 3.2.5 on 2021-07-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_share_survey_publicly'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='acronym',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
