# Generated by Django 3.2.5 on 2021-07-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='acronym',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
