# Generated by Django 3.2.7 on 2021-09-14 08:43

from django.db import migrations

def forward_migration(apps, schema_editor):
    Question = apps.get_model('survey', 'Question')
    SurveyAnswer = apps.get_model('survey', 'SurveyAnswer')
    Question.objects.filter(answer_type='image').update(answer_type='single_image')
    SurveyAnswer.objects.filter(answer_type='image').update(answer_type='single_image')

def backward_migration(apps, schema_editor):
    Question = apps.get_model('survey', 'Question')
    SurveyAnswer = apps.get_model('survey', 'SurveyAnswer')
    Question.objects.filter(answer_type='single_image').update(answer_type='image')
    SurveyAnswer.objects.filter(answer_type='single_image').update(answer_type='image')


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_multiple_image_answer'),
    ]

    operations = [
        migrations.RunPython(forward_migration, backward_migration)
    ]
