# Generated by Django 3.2.7 on 2021-09-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_image_to_single_image_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('date', 'Date'), ('description', 'Description'), ('single_image', 'Single Image'), ('multiple_image', 'Multiple Image'), ('location', 'Location'), ('number', 'Number'), ('text', 'Text'), ('single_option', 'Single Option'), ('multiple_option', 'Multiple Option')], max_length=15),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('date', 'Date'), ('description', 'Description'), ('single_image', 'Single Image'), ('multiple_image', 'Multiple Image'), ('location', 'Location'), ('number', 'Number'), ('text', 'Text'), ('single_option', 'Single Option'), ('multiple_option', 'Multiple Option')], max_length=15),
        ),
    ]
