# Generated by Django 3.2.12 on 2022-02-10 14:40

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_add_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_add_verbose_name'),
        ('survey', '0009_remove_image_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='option',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='option',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='option',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title_en',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title_es',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title_fr',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='option',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='question',
            name='acronym',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='acronym'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('date', 'Date'), ('description', 'Description'), ('single_image', 'Single Image'), ('multiple_image', 'Multiple Image'), ('location', 'Location'), ('number', 'Number'), ('text', 'Text'), ('single_option', 'Single Option'), ('multiple_option', 'Multiple Option')], max_length=15, verbose_name='answer type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.questiongroup', verbose_name='question group'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hints',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='hints'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hints_en',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='hints'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hints_es',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='hints'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hints_fr',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='hints'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='context.module', verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='question',
            name='skip_logic',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='skip logic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_en',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_es',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_fr',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='skip_logic',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='skip logic'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='config',
            field=models.JSONField(default=dict, verbose_name='config'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_shared_publicly',
            field=models.BooleanField(default=False, verbose_name='shared publicly'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='project.project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='shared_link_identifier',
            field=models.CharField(blank=True, default=None, editable=False, max_length=10, null=True, unique=True, verbose_name='shared link identifier'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('date', 'Date'), ('description', 'Description'), ('single_image', 'Single Image'), ('multiple_image', 'Multiple Image'), ('location', 'Location'), ('number', 'Number'), ('text', 'Text'), ('single_option', 'Single Option'), ('multiple_option', 'Multiple Option')], max_length=15, verbose_name='answer type'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='options',
            field=models.ManyToManyField(blank=True, to='survey.Option', verbose_name='options'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.survey', verbose_name='survey'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
