# Generated by Django 3.2.12 on 2022-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_add_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
    ]
