# Generated by Django 3.2.12 on 2022-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_increase_code_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('question', 'survey'), name='unique_survey_question'),
        ),
    ]
