# Generated by Django 3.2.12 on 2022-03-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_surveyanswer_unique_survey_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='mitigation',
            field=models.JSONField(default=list, verbose_name='mitigations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='opportunity',
            field=models.JSONField(default=list, verbose_name='opportunities'),
            preserve_default=False,
        ),
    ]
