# Generated by Django 3.2.12 on 2022-03-23 05:42

from django.db import migrations
from django.db.migrations import exceptions


def forward_migration(apps, schema_editor):
    QuestionGroup = apps.get_model('survey', 'QuestionGroup')
    for group in QuestionGroup.objects.all():
        modules = group.questions.values('module_id').distinct()
        if modules.count() != 1:
            raise exceptions.InvalidMigrationPlan(
                f"Group {group.pk} question doesn't have exactly one module"
            )
        group.module_id = modules.first()["module_id"]
        group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_questiongroup_module'),
    ]

    operations = [
        migrations.RunPython(forward_migration, migrations.RunPython.noop)
    ]
