# Generated by Django 3.2.12 on 2022-03-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_increase_code_max_length'),
        ('survey', '0015_set_question_group_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_groups', to='context.module', verbose_name='module'),
        ),
    ]
