# Generated by Django 3.2.16 on 2023-01-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_remove_question_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='mitigation',
            field=models.JSONField(blank=True, verbose_name='mitigations'),
        ),
        migrations.AlterField(
            model_name='option',
            name='opportunity',
            field=models.JSONField(blank=True, verbose_name='opportunities'),
        ),
    ]
