# Generated by Django 3.2.18 on 2023-02-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_json_field_blank_true_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='mitigation',
        ),
        migrations.RemoveField(
            model_name='option',
            name='opportunity',
        ),
    ]
