# Generated by Django 4.2.17 on 2025-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_alter_surveyanswer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description_en',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description_es',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description_fr',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
    ]
