# Generated by Django 4.2.17 on 2024-12-30 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_increase_code_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0019_alter_surveyanswer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=9, verbose_name='status')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='context.module', verbose_name='module')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='survey.survey', verbose_name='survey')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='surveymodule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('survey', 'module'), name='unique_survey_module_published'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='survey_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveymodule', verbose_name='survey module'),
        ),
        migrations.RemoveConstraint(
            model_name='surveyanswer',
            name='unique_survey_question',
        ),
    ]
