# Generated by Django 4.2.17 on 2024-12-30 04:51

from django.db import migrations
from collections import defaultdict

def forward_migration(apps, schema_editor):
    SurveyModule = apps.get_model('survey', 'SurveyModule')
    SurveyAnswer = apps.get_model('survey', 'SurveyAnswer')

    survey_answers = SurveyAnswer.objects.select_related('question__group__module', 'survey').all()

    survey_modules_data = defaultdict(list)
    for survey_answer in survey_answers:
        module = survey_answer.question.group.module
        survey_modules_data[(survey_answer.survey, module)].append(survey_answer)

    survey_module_map = {}
    for (survey, module), _ in survey_modules_data.items():
        survey_module, _ = SurveyModule.objects.get_or_create(
            survey=survey,
            module=module,
            defaults={'status': 'published'}
        )
        survey_module_map[(survey.id, module.id)] = survey_module.id

    updates = []
    for survey_answer in survey_answers:
        module_id = survey_answer.question.group.module.id
        survey_id = survey_answer.survey.id
        survey_answer.survey_module_id = survey_module_map[(survey_id, module_id)]
        updates.append(survey_answer)
    SurveyAnswer.objects.bulk_update(updates, ['survey_module_id'])

def backward_migration(apps, schema_editor):
    SurveyModule = apps.get_model('survey', 'SurveyModule')
    SurveyModule.objects.exclude(status='published').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_surveymodule_surveyanswer_survey_module'),
    ]

    operations = [
        migrations.RunPython(forward_migration, backward_migration)
    ]
