# Generated by Django 4.2.17 on 2025-01-10 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_add_survey_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='survey_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveymodule', verbose_name='survey module'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('question', 'survey_module'), name='unique_survey_module_question'),
        ),
    ]
