apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert_issuer.yml
  - certificate.yml
patches:
  - patch: |-
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-issuer
      spec:
        acme:
          email: ${CERT_EMAIL_ADDRESS}
    target:
      labelSelector: "app.kubernetes.io/name=letsencrypt-issuer"
  - patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: acme-certificate
      spec:
        dnsNames:
        - ${PROJECT_HOST_URL}
    target:
      labelSelector: "app.kubernetes.io/name=acme-certificate"

