name: Push image

on:
  push:
    branches:
      - develop
      - staging
    tags:
      - v*

env:
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/server
  DOCKER_BUILDKIT: 1

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag server --target production --progress=plain --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_ID

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "develop" ] && VERSION=latest
          echo VERSION=$VERSION
          docker tag server $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
