name: Test Django application

on:
  pull_request:
  push:
    branches:
      - develop

env:
  DOCKER_BUILDKIT: 1

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: 'ENV_'
        env:
          ENV_PROJECT_NAME: "neatplus"
          ENV_SERVER_ENVIRONMENT: "testing"
          ENV_DATABASE_URL: postgis://postgres:postgres@db:5432/postgres
          ENV_POSTGRES_PASSWORD: postgres
          ENV_REDIS_PASSWORD: redis
      - name: Initial external services setup
        run: |
          docker network create external-services
          ln -s docker/external_services.yml external_services.yml
          docker-compose -f external_services.yml up -d
          ln -s docker/docker-compose.test.yml docker-compose.yml
      - name: Run test
        run: |
          docker-compose up --exit-code-from server
