name: Test Django application

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: iamsauravsharma/create-dotenv@v1.1.0
        with:
          env-prefix: 'ENV_'
        env:
          ENV_COMPOSE_PROJECT_NAME: "neatplus-server"
          ENV_SERVER_ENVIRONMENT: "testing"
      - name: Initial docker related setup
        run: |
          docker network create external-services
          ln -s docker-compose.test.yml docker-compose.yml
      - name: Run test
        run: |
          docker-compose up
